USE [master]
GO

/****** Object:  Database [DesafioApi22Dias]    Script Date: 6/28/2023 9:13:57 PM ******/
CREATE DATABASE [DesafioApi22Dias]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DesafioApi22Dias', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DesafioApi22Dias.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DesafioApi22Dias_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\DesafioApi22Dias_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DesafioApi22Dias].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DesafioApi22Dias] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET ARITHABORT OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DesafioApi22Dias] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DesafioApi22Dias] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DesafioApi22Dias] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DesafioApi22Dias] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DesafioApi22Dias] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DesafioApi22Dias] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DesafioApi22Dias] SET  MULTI_USER 
GO

ALTER DATABASE [DesafioApi22Dias] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DesafioApi22Dias] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DesafioApi22Dias] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DesafioApi22Dias] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DesafioApi22Dias] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DesafioApi22Dias] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DesafioApi22Dias] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DesafioApi22Dias] SET  READ_WRITE 
GO

----------------------------------------------------------------------------------------------------------------

USE [DesafioApi21Dias]
GO

/****** Object:  Table [dbo].[tb_alunos]    Script Date: 6/28/2023 9:24:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_alunos](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](150) NOT NULL,
	[matricula] [varchar](8) NOT NULL,
	[notas] [text] NOT NULL,
 CONSTRAINT [PK_tb_alunos] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


----------------------------------------------------------------------------------------------------------------

USE [DesafioApi21Dias]
GO

/****** Object:  Table [dbo].[tb_fornecedor]    Script Date: 6/28/2023 9:24:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tb_fornecedor](
	[cod_cfo] [int] NOT NULL,
	[nome_fantasia] [varchar](150) NOT NULL,
	[razao] [varchar](150) NOT NULL,
	[cpf_cnpj] [varchar](50) NULL,
	[endereco] [varchar](255) NULL,
 CONSTRAINT [PK_fornecedor] PRIMARY KEY CLUSTERED 
(
	[cod_cfo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


